// tslint:disable
/**
 * TrackingAPI
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ConfigurationParameters {
    userId?: string;
    accessToken?: string;
}

export class Configuration {

    userId: string;
    accessToken?: string;

    constructor(param: ConfigurationParameters = {}) {
        this.accessToken = param.accessToken;
        this.userId = param.userId || '';
    }
}
